### ISSUE TITLE
Numeric types don't respect ranges

### ISSUE THREAD

**Issue by antuanPotato** [ilinsky/jquery-xpath#12]
Cast to numeric types that don't respect ranges should not succeed. Consider the following example:

    $().xpath('xs:unsignedByte(10000)');

This **conversion should not succeed as an unsignedByte value can't be more than 255**. The same happens with many other numeric types such as with positiveInteger when passing a negative integer, long, int, etc.

**Comment by antuanPotato** [comment]
In addition casting to *xs:integer* from string can fail. Example

    $().xpath('xs:integer("1000000000000")')

Returns

    [-727379968]

I think this is caused because of the use of the double bitwise not operator ~~, whose operand is converted to signed 32-bit integer inside cXSInteger.cast . Note that xs:integer should have no limit while xs:int should have it.

**Comment by ilinsky** [comment]
Fixed casting to integer in commit 3886231e33a5b4c87fb7e7328543877514022af7 of ilinsky/xpath.js

**Comment by ilinsky** [comment]
Fixed in https://github.com/ilinsky/xpath.js/commit/f2d8ce62deaba09a8c31dc8a3f7ff9de03997cd2
