### ISSUE TITLE
Dot in XML name

### ISSUE THREAD

**Issue by raffazizzi** [ilinsky/jquery-xpath#17]
Parsing an XPath expression with an attribute name containing a dot returns  `Uncaught Error: Unexpected token beyond end of query`.

For example:

```js
xml_element.xpath("@meter.count");
```

Plain jquery `attr()` works correctly:
```js
xml_element.attr("meter.count");
```

Dots are allowed as part of an XML Name, just not at the beginning, so the expression parser should allow them. 

The same issue applies to element names.

**Comment by ilinsky** [comment]
Fixed in ac494f675c5693e6803c3a502d0cdbf7fe859a1f
