### ISSUE TITLE
Use default namespace from context

### ISSUE THREAD

**Issue by ChiSamurai** [ilinsky/jquery-xpath#19]
Hi,

I got an svg embedded in an html page. If I use the jquery selector to get one of the svg-elements, i.e.
`$('svg')` and take this as context for $.xpath(), the context's default namespace is "http://www.w3.org/2000/svg".

Addressing an subelement like the following does not return any element: 
`$('svg').xpath("//rect")`

But using the namespace wildcard works: :
`$('svg').xpath("//*:rect")`

How can I address an element when the default/null namespace is different than html?

Best,
Matthias

**Comment by ilinsky** [comment]
To change default namespace in XPath query you can pass resolver function like this:
`$('svg').xpath("//rect", function() {return "http://www.w3.org/2000/svg"});`

Or:
`$('svg').xpath("//svg:rect", function(prefix) {if (prefix == "svg") return "http://www.w3.org/2000/svg"});`
