### ISSUE TITLE
any CDN hosting this?

### ISSUE THREAD

**Issue by divinity76** [ilinsky/jquery-xpath#24]
is there some CDN hosting this? for people who don't want to host it themselves for whatever reason?

and if there isn't, maybe we could get it into cdnjs or jsdelivr or something like that?

**Comment by MattIPv4** [comment]
Will soon be on cdnjs: https://github.com/cdnjs/packages/pull/435 :)

**Comment by ilinsky** [comment]
Thanks @MattIPv4 

I see library has been now made available at https://cdnjs.com/libraries/jquery-xpath 

The most recent version https://cdnjs.cloudflare.com/ajax/libs/jquery-xpath/0.3.1/jquery.xpath.min.js
