### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by divinity76** [ilinsky/jquery-xpath#25]
what's the license for the library?

and if there isn't any, i recommend adding one, not having a license can deter people from adopting it, 
 licenses i personally like includes: [MIT](https://choosealicense.com/licenses/mit/), [The Unlicense](https://unlicense.org/), and [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by mprins** [comment]
Dual licensed under the MIT and GPL licenses.

https://github.com/ilinsky/jquery-xpath/blob/master/src/jquery-xpath.js#L5

**Comment by divinity76** [comment]
I see, thanks for clearing that up,

ILIKEANAL but i believe the GPL demands that you ship a copy of the GPL with everything GPL-licensed, and i can't seem to find the GPL anywhere in this repo, 

quoting section 4 of GPL v3:

```
  4. Conveying Verbatim Copies.

  You may convey verbatim copies of the Program's source code as you
receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice;
keep intact all notices stating that this License and any
non-permissive terms added in accord with section 7 apply to the code;
keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program.

  You may charge any price or no price for each copy that you convey,
and you may offer support or warranty protection for a fee.
``` 
(source: https://www.gnu.org/licenses/gpl-3.0.txt )

should probably add a copy of both

**Comment by ilinsky** [comment]
License files are in the repo: https://github.com/ilinsky/jquery-xpath/tree/master/res/license
