### ISSUE TITLE
numeric >= and <= don't work for the equals case

### ISSUE THREAD

**Issue by jbmercha** [ilinsky/jquery-xpath#9]
If the following code (and in the >= case) the || operator is always going to return the cXSBoolean object returned by the first call, since it it not a fall like value.
```
if (fXSAnyAtomicType_isNumeric(oLeft)) {
		if (fXSAnyAtomicType_isNumeric(oRight))
			return hStaticContext_operators["numeric-less-than"].call(oContext, oLeft, oRight) || hStaticContext_operators["numeric-equal"].call(oContext, oLeft, oRight);
	}
```
Suggest changing it to
```
if (fXSAnyAtomicType_isNumeric(oLeft)) {
		if (fXSAnyAtomicType_isNumeric(oRight))
		    sOperator = "numeric-greater-than";
	}
```
and letting it fall through like the other cases

**Comment by ilinsky** [comment]
Can you please suggest a test query which would demonstrate the problem?

**Comment by ilinsky** [comment]
Test case: 1>=1 and 1<=1 both returning false for numeric types.
